[courses]
Comp_112 = "Intro to Computer Systems"
Comp_140 = "HCI"
Comp_176 = "Operating Systems"
Engl_170 = "Technical Communications 1"
Math_163 = "Mathematics for Computing"

Busi_143 = "Foundation of eBusiness"
Comp_132 = "Object-Oriented Programming in Java"
Comp_170 = "Computer/Network Operations"
Comp_183 = "Computer Architecture"
Comp_155 = "Database Concepts"

Comp_139 = "Applied Programming"
Comp_157 = "Windows Applications"
Comp_173 = "Networking Programming"
Comp_235 = "Software Engineering"
Comp_199 = "Year One Project"

Comp_230 = "Systems Analysis and Design"
Comp_288 = "Embedded Systems"
Comp_241 = ".NET Web Applications"
Comp_270 = "Computer Operations"
Comp_272 = "Intro to Data Communications"
Comp_297 = "Capstone Project Prep"

Comp_244 = "Distrubuted Systems Networking"
Comp_259 = "Database Development Tools"
Comp_249 = "Oracle Database Advanced"
Comp_289 = "Concurrent Programming"
Comp_298 = "Capstone Project Analysis"

Engl_273 = "Technical Communication 2"
Comp_275 = "System Security"
Comp_299 = "Capstone Implementation"
Tech_290 = "Symposium"
